version: "3.8"

services:
  web:
    image: nginx:alpine
    command:
      - /bin/sh
      - -c
      - |
        echo "SWARM TASK: $$(hostname)" > /usr/share/nginx/html/index.html
        exec nginx -g 'daemon off;'
    ports:
      - target: 80
        published: 8088
        protocol: tcp
        mode: ingress
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
